# Generated by Django 3.2.2 on 2021-06-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_tag'),
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='tag',
            field=models.ManyToManyField(blank=True, to='common.Tag'),
        ),
    ]
