# Generated by Django 3.2.2 on 2021-05-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('regional moderator', 'Regional moderator'), ('user', 'User')], default='user', max_length=30),
        ),
    ]
