# Generated by Django 3.2.2 on 2021-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_city'),
        ('account', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='user', to='event.City', verbose_name='Город(a) пользователя'),
        ),
    ]
