# Generated by Django 3.2.2 on 2021-05-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_city_user'),
        ('account', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(related_name='user', to='event.City', verbose_name='Город(a) пользователя'),
        ),
    ]
