# Generated by Django 3.2.2 on 2021-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_city_user'),
        ('account', '0009_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='user', to='event.City', verbose_name='Город(a) пользователя'),
        ),
    ]
