# Generated by Django 3.2.2 on 2021-05-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210521_1948'),
        ('account', '0010_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='user', to='event.City', verbose_name='Город(a) пользователя'),
        ),
    ]
