# Generated by Django 3.2.2 on 2021-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('regional moderator', 'Regional moderator'), ('mentor', 'Mentor')], default='mentor', max_length=30, verbose_name='Роль пользователя'),
        ),
    ]
