# Generated by Django 3.2.2 on 2021-05-21 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_city_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='user',
            field=models.ManyToManyField(related_name='city', to=settings.AUTH_USER_MODEL),
        ),
    ]
