# Generated by Django 3.2.2 on 2021-05-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_city_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
