# Generated by Django 3.2.2 on 2021-05-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210521_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
