# Generated by Django 3.2.2 on 2021-05-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_event_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booked',
        ),
    ]
