# Generated by Django 3.2.2 on 2021-05-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_event_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='event.event'),
        ),
    ]
