# Generated by Django 3.2.2 on 2021-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_eventparticipant_event'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='event'),
        ),
    ]
