# Generated by Django 3.2.2 on 2021-05-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20210524_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя города присутствия проекта BBBS'),
        ),
    ]
