# Generated by Django 3.2.3 on 2021-05-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_eventparticipant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='afisha.event'),
        ),
    ]
