# Generated by Django 3.2.2 on 2021-06-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='common.city'),
        ),
    ]
