# Generated by Django 3.2.3 on 2021-05-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('Наставник', 'Mentor'), ('Модератор', 'Moderator'), ('Региональный модератор', 'Regional Moderator'), ('Администратор', 'Admin')], default='Наставник', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Первичный(???)'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='common.city', verbose_name='Город'),
        ),
    ]
