# Generated by Django 3.2.2 on 2021-06-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-is_primary'], 'verbose_name_plural': 'Cities'},
        ),
    ]
